export enum TaskType {
  LAUNCH_BROWSER = 'LAUNCH_BROWSER',
  PAGE_TO_HTML = 'PAGE_TO_HTML',
  EXTRACT_TEXT_FROM_ELEMENT = 'EXTRACT_TEXT_FROM_ELEMENT',
  FILL_INPUT = 'FILL_INPUT',
  TYPE_INPUT = 'TYPE_INPUT',
  CLICK_ELEMENT = 'CLICK_ELEMENT',
  WAIT_FOR_ELEMENT = 'WAIT_FOR_ELEMENT',
  DELIVER_VIA_WEBHOOK = 'DELIVER_VIA_WEBHOOK',
  EXTRACT_DATA_WITH_AI = 'EXTRACT_DATA_WITH_AI',
  READ_PROPERTY_FROM_JSON = 'READ_PROPERTY_FROM_JSON',
  ADD_PROPERTY_TO_JSON = 'ADD_PROPERTY_TO_JSON',
  NAVIGATE_URL = 'NAVIGATE_URL',
  SCROLL_TO_ELEMENT = 'SCROLL_TO_ELEMENT',
  TAKE_SCREENSHOT = 'TAKE_SCREENSHOT',
  // Enhanced tasks
  WAIT_DELAY = 'WAIT_DELAY',
  EXTRACT_TABLE_DATA = 'EXTRACT_TABLE_DATA',
  CONDITIONAL_LOGIC = 'CONDITIONAL_LOGIC',
  DATA_TRANSFORM = 'DATA_TRANSFORM',
  DOWNLOAD_FILE = 'DOWNLOAD_FILE',
  SEND_EMAIL = 'SEND_EMAIL',
  LOOP = 'LOOP',
  FILTER_DATA = 'FILTER_DATA',
  SELECT_OPTION = 'SELECT_OPTION',
  UPLOAD_FILES = 'UPLOAD_FILES',
  SOLVE_CAPTCHA = 'SOLVE_CAPTCHA',
  // Advanced extraction
  EXTRACT_CSS_FROM_PAGE = 'EXTRACT_CSS_FROM_PAGE',
  EXTRACT_XPATH_FROM_PAGE = 'EXTRACT_XPATH_FROM_PAGE',
  EXTRACT_LINKS_FROM_PAGE = 'EXTRACT_LINKS_FROM_PAGE',
  INTERCEPT_NETWORK = 'INTERCEPT_NETWORK',
  GRAPHQL_QUERY = 'GRAPHQL_QUERY',
  GENERATE_SELECTOR_AI = 'GENERATE_SELECTOR_AI',
  INFINITE_SCROLL = 'INFINITE_SCROLL',
  SET_USER_AGENT = 'SET_USER_AGENT',
  WAIT_NETWORK_IDLE = 'WAIT_NETWORK_IDLE',
  REST_REQUEST = 'REST_REQUEST',
  EXTRACT_ATTRIBUTE_FROM_ELEMENT = 'EXTRACT_ATTRIBUTE_FROM_ELEMENT',
  HOVER_ELEMENT = 'HOVER_ELEMENT',
  DOUBLE_CLICK_ELEMENT = 'DOUBLE_CLICK_ELEMENT',
  DRAG_AND_DROP = 'DRAG_AND_DROP',
  PRESS_KEY = 'PRESS_KEY',
  SUBMIT_FORM = 'SUBMIT_FORM',
  WAIT_FOR_NAVIGATION = 'WAIT_FOR_NAVIGATION',
  WAIT_FOR_SELECTOR_HIDDEN = 'WAIT_FOR_SELECTOR_HIDDEN',
  EXTRACT_HTML_FROM_ELEMENT = 'EXTRACT_HTML_FROM_ELEMENT',
  EXTRACT_JSONLD = 'EXTRACT_JSONLD',
  REGEX_EXTRACT = 'REGEX_EXTRACT',
  SET_EXTRA_HEADERS = 'SET_EXTRA_HEADERS',
  SET_VIEWPORT_SIZE = 'SET_VIEWPORT_SIZE',
  PAGINATE_NEXT_BUTTON = 'PAGINATE_NEXT_BUTTON',
  EVALUATE_SCRIPT = 'EVALUATE_SCRIPT',
}

export enum TaskCategory {
  BROWSER = 'BROWSER',
  INTERACTION = 'INTERACTION',
  EXTRACTION = 'EXTRACTION',
  STORAGE = 'STORAGE',
  TIMING = 'TIMING',
  DELIVERY = 'DELIVERY',
  AI = 'AI',
  ADVANCED = 'ADVANCED',
  COMMUNICATION = 'COMMUNICATION',
}

export enum TaskParamType {
  STRING = 'STRING',
  BROWSER_INSTANCE = 'BROWSER_INSTANCE',
  SELECT = 'SELECT',
  CREDENTIAL = 'CREDENTIAL',
  NUMBER = 'NUMBER',
  BOOLEAN = 'BOOLEAN',
  TEXTAREA = 'TEXTAREA',
  JSON = 'JSON',
}

export interface TaskParam {
  name: string;
  type: TaskParamType;
  helperText?: string;
  required?: boolean;
  hideHandle?: boolean;
  value?: string;
  [key: string]: any;
}
